version: '3'
services:
  app:
    build: .
    ports:
      - "3000: 9000"
    dependes_on:
      - database
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: teste
